spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AccesoaDatos?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: spring-clientes-api

server:
  port: 8080